# Server
server.port=${PORT:8080}

# MySQL
spring.datasource.url=jdbc:mysql://hopper.proxy.rlwy.net:35612/railway?useSSL=false&serverTimezone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=NFFkNnYmpyrCRUeXtvlXmcpaVTcCCWyD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Connection Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

# Logging
logging.level.com.nishacollection=INFO

# CORS
app.cors.allowed-origins=https://nishacollection.vercel.app

# Admin credentials (change these!)
app.admin.username=${ADMIN_USERNAME:admin}
app.admin.password=${ADMIN_PASSWORD:nisha@123}
